nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.0.2.cjs

installConfig.immutable: false # turn off this to allow yarn to update the yarn.lock file; this is to prevent yarn install from interruption in the Release Github Actions