#!/usr/bin/env node
const fs = require("fs");


process.chdir("packages");
const dirs = fs.readdirSync(".")

process.chdir(`api-augment/build`);
const aaPkg = JSON.parse(fs.readFileSync('../package.json'));

aaPkg.scripts = {};
aaPkg.main = "./index.cjs";
aaPkg.module = "./index.js";
aaPkg.types = "./index.d.ts";
fs.writeFileSync("./package.json", JSON.stringify(aaPkg, null, 2));
fs.copyFileSync("../../../templates/index.cjs", "./index.cjs");

process.chdir("../..");
process.chdir(`types/build`);
const tPkg = JSON.parse(fs.readFileSync('../package.json'));

tPkg.scripts = {};
tPkg.main = "./index.js";
tPkg.types = "./index.d.ts";
fs.writeFileSync("./package.json", JSON.stringify(tPkg, null, 2));

process.chdir("../..");
process.chdir(`config/build`);
const configPkg = JSON.parse(fs.readFileSync('../package.json'));

configPkg.scripts = {};
configPkg.main = "./index.js";
configPkg.types = "./index.d.ts";
fs.writeFileSync("./package.json", JSON.stringify(configPkg, null, 2));
fs.copyFileSync("../../../templates/index.cjs", "./index.cjs");

process.chdir("../..");
process.chdir(`sdk/build`);
const sdkPkg = JSON.parse(fs.readFileSync('../package.json'));

sdkPkg.scripts = {};
sdkPkg.main = "./index.js";
sdkPkg.types = "./index.d.ts";
fs.writeFileSync("./package.json", JSON.stringify(sdkPkg, null, 2));
fs.copyFileSync("../../../templates/index.cjs", "./index.cjs");

process.chdir("../..");
process.chdir(`adapter/build`);
const adapterPkg = JSON.parse(fs.readFileSync('../package.json'));

adapterPkg.scripts = {};
adapterPkg.main = "./index.js";
adapterPkg.types = "./index.d.ts";
fs.writeFileSync("./package.json", JSON.stringify(adapterPkg, null, 2));
fs.copyFileSync("../../../templates/index.cjs", "./index.cjs");

process.chdir("../..");
