#!/usr/bin/env bash

# Publish packages to npm
# usage: npm run publish -- <version> <otp>
# Publish production version: npm run publish -- 1.9.0 111111
# Publish release-candidate version: npm run publish -- 1.9.0-rc.1 111111
version=$1
otp=$2

# Read tag from version string
# version: 1.9.0-rc.123, tag: rc
if [[ $version =~ .+-.+ ]];
then
  [[ $version =~ .+-(.+)\..+ ]] && tag_option="--tag ${BASH_REMATCH[1]}"
  if [[ -z ${tag_option} ]];
  then
    echo 'Version format is incorrect!'
  fi
fi

# Publish packages to npm
npm pkg set version=$version

for package in $(ls packages); do
  cd packages/$package/build
  npm pkg set version=$version
  npm publish $tag_option --otp $otp
  cd -
done
