name: Release

on:
  push:
    branches:
      - main
      - test_workflow_branch

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 18.x
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm ci --ignore-scripts

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          title: Changeset Version Bump
          commit: Update the version of packages with .changeset md files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # - name: Update Pull Request Body
      #   run: node .github/scripts/update-pr.js
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # TODO: retrieve the tag, add it to PR title, and add the tags Tags {NewTag} to the PR body, so we can tag the code upon merge with tag-release-on-pr-merged.yml